### Librerias

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import HTML, display
import tabulate
import networkx as nx
from random import random as rand
import itertools
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

In [ ]:
data = pd.read_csv("/content/autos.csv")

# Codificar las columnas categóricas utilizando Label Encoding
label_encoder = LabelEncoder()

# Iterar sobre las columnas y aplicar Label Encoding a las categóricas
for column in data.columns:
    if data[column].dtype == 'object':
        data[column] = label_encoder.fit_transform(data[column])
data

Brand  Model  Motor  Door Number  Fuel Type  Engine Location  Sportscar  \
0      31      7      3            4          2                0          0   
1      11     25      7            2          2                0          1   
2       4      1      4            4          2                0          0   
3       8     36      7            4          2                0          0   
4      25     14      4            4          0                0          0   
5       3     28      6            4          2                0          0   
6      10      0      7            2          2                1          1   
7      13      5      3            4          2                0          0   
8      28     27      5            4          2                0          0   
9      27      8      6            4          2                0          0   
10     26      3      3            4          2                0          0   
11     19      4      5            2          2                1          1   
12     14     34      6            4          2                0          0   
13     22     30      7            4          2                0          0   
14     29     26      2            4          2                0          0   
15      5     10      7            2          2                0          1   
16     18     35      3            4          2                0          0   
17      2     12      5            2          2                0          1   
18     29     20      1            4          2                0          0   
19     16     19      6            2          2                0          1   
20     17     37      6            2          2                0          0   
21     20     13      6            4          0                0          0   
22      9      9      7            4          2                0          0   
23     32     38      3            4          2                0          0   
24     30     24      0            4          1                0          1   
25     29     23      1            4          2                0          0   
26      7     18      7            4          2                0          0   
27      6     16      6            4          2                0          0   
28      1     22      3            4          2                0          1   
29      0     31      6            4          2                0          0   
30     21     32      6            4          2                0          0   
31     29     11      1            4          2                0          0   
32     15     29      6            4          2                0          0   
33     24      2      7            2          2                1          1   
34     14     15      3            4          2                0          0   
35     20     33      7            4          0                0          0   
36      6     17      3            4          2                0          0   
37     12     21      3            4          2                0          1   
38     23      6      3            4          2                0          0   

    Luxurious  Family  SUV  
0           0       1    0  
1           0       0    0  
2           1       0    0  
3           1       1    1  
4           1       0    0  
5           0       0    1  
6           1       0    0  
7           0       1    1  
8           1       0    0  
9           0       0    1  
10          0       1    0  
11          1       0    0  
12          0       0    1  
13          1       0    0  
14          0       1    1  
15          1       0    0  
16          0       0    1  
17          1       0    0  
18          0       1    1  
19          1       0    0  
20          0       1    1  
21          1       1    1  
22          0       0    0  
23          1       1    1  
24          1       1    0  
25          0       1    0  
26          1       0    1  
27          0       1    1  
28

In [ ]:
def sigmoid(x):
    return 1 / ( 1 + np.exp(-x) )


def sigmoid_derivative(x):
    return x * (1 - x)

Se define la función de activación sigmoidal en las funciones sigmoid(x) y sigmoid_derivative(x). La función sigmoid(x) se usa para calcular las salidas de la red neuronal y sigmoid_derivative(x) se usa en el cálculo de ajustes de pesos durante el entrenamiento.

In [ ]:
training_inputs = data.drop(columns=['Sportscar','Luxurious','Family','SUV'])

training_outputs = data[['Sportscar','Luxurious','Family','SUV']]

display(training_inputs)
display(training_outputs)

Brand  Model  Motor  Door Number  Fuel Type  Engine Location
0      31      7      3            4          2                0
1      11     25      7            2          2                0
2       4      1      4            4          2                0
3       8     36      7            4          2                0
4      25     14      4            4          0                0
5       3     28      6            4          2                0
6      10      0      7            2          2                1
7      13      5      3            4          2                0
8      28     27      5            4          2                0
9      27      8      6            4          2                0
10     26      3      3            4          2                0
11     19      4      5            2          2                1
12     14     34      6            4          2                0
13     22     30      7            4          2                0
14     29     26      2            4          2                0
15      5     10      7            2          2                0
16     18     35      3            4          2                0
17      2     12      5            2          2                0
18     29     20      1            4          2                0
19     16     19      6            2          2                0
20     17     37      6            2          2                0
21     20     13      6            4          0                0
22      9      9      7            4          2                0
23     32     38      3            4          2                0
24     30     24      0            4          1                0
25     29     23      1            4          2                0
26      7     18      7            4          2                0
27      6     16      6            4          2                0
28      1     22      3            4          2                0
29      0     31      6            4          2                0
30     21     32      6            4          2                0
31     29     11      1            4          2                0
32     15     29      6            4          2                0
33     24      2      7            2          2                1
34     14     15      3            4          2                0
35     20     33      7            4          0                0
36      6     17      3            4          2                0
37     12     21      3            4          2                0
38     23      6      3            4          2                0

Sportscar  Luxurious  Family  SUV
0           0          0       1    0
1           1          0       0    0
2           0          1       0    0
3           0          1       1    1
4           0          1       0    0
5           0          0       0    1
6           1          1       0    0
7           0          0       1    1
8           0          1       0    0
9           0          0       0    1
10          0          0       1    0
11          1          1       0    0
12          0          0       0    1
13          0          1       0    0
14          0          0       1    1
15          1          1       0    0
16          0          0       0    1
17          1          1       0    0
18          0          0       1    1
19          1          1       0    0
20          0          0       1    1
21          0          1       1    1
22          0          0       0    0
23          0          1       1    1
24          1          1       1    0
25          0          0       1    0
26          0          1       0    1
27          0          0       1    1
28          1          1       0    0
29          0          0       0    1
30          0          1       1    1
31          0          0       1    1
32          0          1       1    1
33          1          1       0    0
34          0          0       1    0
35          0          1       0    1
36          0          0       1    1
37          1          1       0    0
38          0          0       1    1

In [ ]:
n = training_inputs.shape[1]
k = training_outputs.shape[1]
print(n, k)
synaptic_weights = np.random.random((n, k))

synaptic_weights

6 4


array([[0.45411442, 0.42456226, 0.40381925, 0.73204034],
       [0.14033301, 0.9529204 , 0.81826517, 0.07991612],
       [0.23785257, 0.81363531, 0.17570042, 0.29076251],
       [0.22182424, 0.24379333, 0.1504401 , 0.39598436],
       [0.61508954, 0.33290426, 0.25482382, 0.68149508],
       [0.7427678 , 0.94269461, 0.47114418, 0.94599263]])

In [ ]:
eval_NN = lambda x, w: sigmoid(np.dot(x, w))

In [ ]:
# 50000 epochs
for iteration in range(5000):

    # Arranca con los valores de training
    input_layer = training_inputs

    # Genera un output haciendo la suma de los valores de input multiplicados por su peso sinaptico, y aplicandole la función sigmoide para normalizar a -1, 1
    outputs = eval_NN(input_layer, synaptic_weights)

    # Calculo el error
    error = training_outputs - outputs
    #display(error)
    # Ajusto los pesos en funcion al error y al resultado obtenido
    adjustments = error * sigmoid_derivative(outputs)
    synaptic_weights += np.dot(input_layer.T, adjustments)


El proceso de forward propagation se realiza en el bucle for iteration in range(5000) donde se calculan las salidas de la red neuronal (outputs) mediante la función eval_NN(input_layer, synaptic_weights). Aquí, se multiplican las entradas por los pesos sinápticos y se aplica la función sigmoidal para normalizar los resultados.

El proceso de back propagation se realiza en las siguientes líneas:
Se calcula el error entre las salidas deseadas (training_outputs) y las salidas de la red (outputs) en error = training_outputs - outputs.
Luego, se calculan los ajustes de pesos (adjustments) utilizando el error y la derivada de la función sigmoidal en adjustments = error * sigmoid_derivative(outputs).
Finalmente, se actualizan los pesos sinápticos en synaptic_weights += np.dot(input_layer.T, adjustments).
El gradiente descendente se aplica indirectamente durante el proceso de back propagation. Los pesos sinápticos se ajustan, lo que es un paso esencial en el entrenamiento de la red neuronal para minimizar la función de pérdida.

In [ ]:
print('Synaptic weights after training')
print(synaptic_weights)

print('Outputs after training: ')
print(outputs)

Synaptic weights after training
[[-1.36635745 -7.60156333  1.35156259  1.37505203]
 [-6.87802169 -0.63214269  5.09351314  4.4544989 ]
 [-0.09263465 -0.07417912 -3.18667969  0.6133173 ]
 [-2.11081064 -0.98341214 -1.45406238  0.80937131]
 [ 0.17793454 -0.2790381  -0.86524431  0.68620035]
 [ 1.10402245  0.944355    0.15427807  0.94596632]]
Outputs after training: 
[[1.15330929e-043 4.89826393e-107 1.00000000e+000 1.00000000e+000]
 [6.83784256e-084 3.16265203e-045 1.00000000e+000 1.00000000e+000]
 [9.24871153e-010 2.75805090e-016 5.58003334e-005 9.99999959e-001]
 [8.38960771e-117 3.38785314e-039 1.00000000e+000 1.00000000e+000]
 [3.29583132e-061 6.11428198e-089 1.00000000e+000 1.00000000e+000]
 [6.72474442e-090 1.84083075e-020 1.00000000e+000 1.00000000e+000]
 [3.84559288e-008 1.18822496e-034 1.71614656e-006 1.00000000e+000]
 [5.21614400e-027 4.60066347e-047 1.00000000e+000 1.00000000e+000]
 [1.04701223e-101 1.09355433e-102 1.00000000e+000 1.00000000e+000]
 [2.12702744e-044 3.34293072e-094

In [ ]:
large = lambda x : display(HTML('<p style="font-size: 50px; color: #66D148">'+str(x)+'</p>'))

In [ ]:
a = 1 #@param {type:"integer"}
c = 1 #@param {type:"integer"}
b = 0 #@param {type:"integer"}
d = 0 #@param {type:"integer"}
e = 0 #@param {type:"integer"}
f = 1 #@param {type:"integer"}


input_layer = np.array([a, b, c, d, e, f])
res = sigmoid(np.dot(input_layer, synaptic_weights))
display(res)

thresh = 0.01
out = np.where(res < thresh,0,1)

large(out)

array([0.41217781, 0.00119146, 0.1569844 , 0.9495179 ])

La función Softmax se usa para problemas en los que cada ejemplo de entrada debe pertenecer a una y solo una categoría. Para utilizar Softmax, debes asegurarte de que la capa de salida utilice esta función en lugar de la sigmoide o ReLU. Softmax asigna una probabilidad a cada categoría y garantiza que todas las probabilidades sumen 1. También debes ajustar la función de pérdida en tu código para que sea compatible con Softmax en lugar de la función de pérdida anterior.

No se define explícitamente la estructura de la red, como el número de capas ocultas o la cantidad de neuronas en cada capa. En su lugar, la estructura de la red se infiere de los datos de entrada y salida. En este caso, la red es un perceptrón multicapa (MLP) con una capa de entrada y una capa de salida.